export interface AdminTool {
  id: string;
  label: string;
  description: string;
  href: string;
  keywords: string[];
  group: 'Content' | 'Monetization' | 'Email' | 'Ops';
  iconName: string;
}

export const ADMIN_TOOLS: AdminTool[] = [
  {
    id: 'top25-editor',
    label: 'Edit Top-25 Pages',
    description: 'Edit state page content, agencies, and spotlights',
    href: '/wp-admin/top25-editor',
    keywords: ['top25', 'state', 'edit', 'agencies', 'spotlight', 'content'],
    group: 'Content',
    iconName: 'Edit2',
  },
  {
    id: 'json-import',
    label: 'Import Top-25 Agencies',
    description: 'Bulk import agencies from JSON files into state directories',
    href: '/wp-admin/json-import',
    keywords: ['import', 'json', 'bulk', 'agencies', 'states'],
    group: 'Content',
    iconName: 'FileJson',
  },
  {
    id: 'other-agencies-import',
    label: 'Import Other Agencies',
    description: 'Import local agencies per state (CSV/JSON) for "Other Agencies" section with email splitting',
    href: '/wp-admin/other-agencies-import',
    keywords: ['import', 'csv', 'json', 'agencies', 'bulk', 'local', 'other', 'state', 'email'],
    group: 'Content',
    iconName: 'Upload',
  },
  {
    id: 'other-agencies-import-v2',
    label: 'Import Other Agencies V2',
    description: 'Clean-room V2 import — real background processing, real progress, large file support, no fake success',
    href: '/wp-admin/other-agencies-import-v2',
    keywords: ['import', 'v2', 'csv', 'xlsx', 'agencies', 'bulk', 'local', 'other', 'state', 'email', 'background'],
    group: 'Content',
    iconName: 'UploadCloud',
  },
  {
    id: 'other-agencies-manager',
    label: 'Other Agencies Manager',
    description: 'Manage bulk agency listings — badges, website URLs, visibility, and paid status overrides',
    href: '/wp-admin/other-agencies-manager',
    keywords: ['other', 'agencies', 'badges', 'website', 'paid', 'status', 'manager', 'bulk', 'override', 'active'],
    group: 'Content',
    iconName: 'Building2',
  },
  {
    id: 'email-cleaning',
    label: 'Email Cleaning Workflow',
    description: 'Export agency emails for cleaning/validation, then import validated results back',
    href: '/wp-admin/email-cleaning',
    keywords: ['email', 'cleaning', 'validation', 'export', 'import', 'zerobounce', 'neverbounce', 'agencies'],
    group: 'Content',
    iconName: 'MailOpen',
  },
  {
    id: 'smartlead',
    label: 'Smartlead Sync',
    description: 'Sync clean agency contacts to Smartlead campaigns with eligibility filters and engagement tracking',
    href: '/wp-admin/smartlead',
    keywords: ['smartlead', 'sync', 'campaigns', 'outreach', 'agencies', 'contacts', 'engagement', 'leads', 'reply', 'bounce'],
    group: 'Content',
    iconName: 'Send',
  },
  {
    id: 'logo-upload',
    label: 'Bulk Logo Upload',
    description: 'Upload and manage agency logos for state listings',
    href: '/wp-admin/logo-upload',
    keywords: ['logo', 'image', 'upload', 'agencies'],
    group: 'Content',
    iconName: 'Image',
  },
  {
    id: 'agency-reviews',
    label: 'Agency Reviews',
    description: 'Review and manage agency review submissions',
    href: '/wp-admin/agency-reviews',
    keywords: ['reviews', 'ratings', 'agency', 'submissions'],
    group: 'Content',
    iconName: 'Star',
  },
  {
    id: 'agency-reviews-import',
    label: 'Import Agency Reviews',
    description: 'Bulk import agency reviews from CSV or JSON with validation and uniqueness scoring',
    href: '/wp-admin/agency-reviews/import',
    keywords: ['reviews', 'import', 'bulk', 'csv', 'json', 'agency', 'upload', 'uniqueness'],
    group: 'Content',
    iconName: 'Upload',
  },
  {
    id: 'tools',
    label: 'Tools',
    description: 'Manage the Tools directory — entities, categories, and tags',
    href: '/wp-admin/tools',
    keywords: ['tools', 'directory', 'entities', 'categories', 'tags', 'software'],
    group: 'Content',
    iconName: 'Wrench',
  },
  {
    id: 'sidebar-ads',
    label: 'Homepage Ads',
    description: 'Manage sidebar advertisement placements on homepage',
    href: '/wp-admin/sidebar-ads',
    keywords: ['ads', 'sidebar', 'homepage', 'advertising', 'banners'],
    group: 'Monetization',
    iconName: 'LayoutGrid',
  },
  {
    id: 'stripe',
    label: 'Revenue',
    description: 'Revenue analytics, orders, subscriptions, and Stripe sync',
    href: '/wp-admin/revenue',
    keywords: ['stripe', 'revenue', 'orders', 'payments', 'subscriptions', 'billing'],
    group: 'Monetization',
    iconName: 'CreditCard',
  },
  {
    id: 'revenue-health',
    label: 'Revenue Health',
    description: 'Top-25 slot inventory status, audit log, and availability self-test',
    href: '/wp-admin/revenue-health',
    keywords: ['revenue', 'health', 'slots', 'inventory', 'audit', 'self-test', 'availability', 'locked', 'sold'],
    group: 'Monetization',
    iconName: 'Activity',
  },
  {
    id: 'thank-you-page',
    label: 'Thank-you Page',
    description: 'Test and preview thank-you page states without Stripe (QA tool)',
    href: '/wp-admin/thank-you-page',
    keywords: ['thank-you', 'payment', 'order', 'complete', 'preview', 'test', 'qa', 'validation', 'post-payment', 'editor'],
    group: 'Monetization',
    iconName: 'CheckCircle',
  },
  {
    id: 'customer-suppression',
    label: 'Customer Suppression',
    description: 'Block paid agencies from Smartlead exports — agency-level do-not-contact protection',
    href: '/wp-admin/customer-suppression',
    keywords: ['suppression', 'paid', 'customer', 'do not contact', 'smartlead', 'exclude', 'opt out', 'blocked', 'agency'],
    group: 'Email',
    iconName: 'ShieldOff',
  },
  {
    id: 'em-overview',
    label: 'Email',
    description: 'Email marketing — campaigns, automations, audience, SMTP configuration',
    href: '/wp-admin/email/overview',
    keywords: ['email', 'marketing', 'dashboard', 'kpi', 'overview', 'campaigns', 'automations', 'smtp', 'audience', 'segments', 'templates', 'logs'],
    group: 'Email',
    iconName: 'Mail',
  },
  {
    id: 'smartlead-inbox',
    label: 'Cold Outreach Inbox',
    description: 'CRM inbox for Smartlead conversations — replies, agency enrichment, funnel context',
    href: '/wp-admin/email/smartlead/inbox',
    keywords: ['smartlead', 'inbox', 'crm', 'conversations', 'replies', 'cold outreach', 'leads', 'agency'],
    group: 'Email',
    iconName: 'Inbox',
  },
  {
    id: 'contact-inbox',
    label: 'Contact Inbox',
    description: 'Manage website contact form submissions with CRM enrichment and SMTP reply',
    href: '/wp-admin/contact-inbox',
    keywords: ['contact', 'inbox', 'messages', 'form', 'submissions', 'reply', 'smtp', 'crm'],
    group: 'Email',
    iconName: 'MessageSquare',
  },
  {
    id: 'agency-reply-helper',
    label: 'Agency Reply Helper',
    description: 'Find agency by email and copy /your-agency URL for Smartlead manual replies',
    href: '/wp-admin/email/agency-lookup',
    keywords: ['email', 'lookup', 'agency', 'reply', 'smartlead', 'your-agency', 'url', 'copy', 'manual'],
    group: 'Email',
    iconName: 'UserSearch',
  },
  {
    id: 'submissions',
    label: 'Submissions Center',
    description: 'All form submissions with funnel tracking and timelines',
    href: '/wp-admin/submissions',
    keywords: ['submissions', 'leads', 'forms', 'funnel', 'tracking', 'get matched', 'spotlight', 'availability'],
    group: 'Ops',
    iconName: 'Inbox',
  },
  {
    id: 'funnel-analytics',
    label: 'Funnel Analytics',
    description: 'Session progression, step-level events, conversion rates, and drop-off analysis across all funnels',
    href: '/wp-admin/analytics/funnels',
    keywords: ['funnel', 'analytics', 'conversion', 'sessions', 'events', 'steps', 'drop-off', 'tracking', 'your agency', 'demo'],
    group: 'Ops',
    iconName: 'TrendingUp',
  },
  {
    id: 'product-funnel',
    label: 'Product Funnel',
    description: 'Internal Gappsy product events across 5 funnel sources, deduped by agency. Hot Agencies, step breakdown, quick outreach links.',
    href: '/wp-admin/analytics/product-funnel',
    keywords: ['product', 'funnel', 'intelligence', 'hot', 'unpaid', 'your agency', 'replay', 'availability', 'manage', 'activation', 'checkout', 'discount'],
    group: 'Ops',
    iconName: 'Flame',
  },
  {
    id: 'agency-funnel-analytics',
    label: 'Agency Funnel',
    description: 'Per-agency funnel analytics — entry paths, engagement, drop-off, and conversion tracking',
    href: '/wp-admin/analytics/agency-funnel',
    keywords: ['agency', 'funnel', 'analytics', 'conversion', 'drop-off', 'engagement', 'your agency', 'scroll', 'time', 'search', 'direct'],
    group: 'Ops',
    iconName: 'Target',
  },
  {
    id: 'activity-feed',
    label: 'Activity Feed',
    description: 'Real-time unified stream of all agency events — views, engagement, conversions, and negatives across every funnel',
    href: '/wp-admin/activity-feed',
    keywords: ['activity', 'feed', 'live', 'realtime', 'events', 'stream', 'timeline', 'agency', 'intent', 'signals'],
    group: 'Ops',
    iconName: 'Activity',
  },
  {
    id: 'intent-center',
    label: 'Intent Center',
    description: 'Hot agencies right now — intent scores, recent activity, HOT NOW signals, and follow-up helpers',
    href: '/wp-admin/intent-center',
    keywords: ['intent', 'hot', 'score', 'activity', 'replay', 'availability', 'checkout', 'follow-up', 'signals', 'priority'],
    group: 'Ops',
    iconName: 'Flame',
  },
  {
    id: 'manage-removals',
    label: 'Manage Removals',
    description: 'Audit self-removed listings — hidden by owner, recovery events, remove intent, and timeline history',
    href: '/wp-admin/manage-removals',
    keywords: ['manage', 'removals', 'hidden', 'self-removed', 'removal_pending', 'recovery', 'remove intent', 'listing', 'owner', 'funnel'],
    group: 'Ops',
    iconName: 'EyeOff',
  },
  {
    id: 'availability-analytics',
    label: 'Availability Analytics',
    description: 'Agency leaderboard, availability request trends, and per-agency stats',
    href: '/wp-admin/availability-analytics',
    keywords: ['availability', 'analytics', 'leaderboard', 'agencies', 'requests', 'clicks', 'stats', 'trends'],
    group: 'Ops',
    iconName: 'BarChart2',
  },
  {
    id: 'email-notifications',
    label: 'Email Notifications',
    description: 'Configure internal admin notifications for all form submissions',
    href: '/wp-admin/email-notifications',
    keywords: ['email', 'notifications', 'alerts', 'forms', 'submissions', 'smtp', 'recipients', 'notify'],
    group: 'Ops',
    iconName: 'Bell',
  },
  {
    id: 'agency-email-automations',
    label: 'Agency Email Automations',
    description: 'Control automated emails sent to agencies for availability checks (currently disabled)',
    href: '/wp-admin/agency-email-automations',
    keywords: ['agency', 'email', 'automations', 'availability', 'leads', 'digest', 'paid', 'unpaid'],
    group: 'Ops',
    iconName: 'Zap',
  },
  {
    id: 'agency-dedup',
    label: 'Agency Dedup & Repair',
    description: 'Detect duplicate agency records, preview safe merges with email-ownership rules, eliminate competing /your-agency URLs',
    href: '/wp-admin/agency-dedup',
    keywords: ['dedup', 'duplicate', 'agency', 'merge', 'repair', 'identity', 'conflict', 'your-agency', 'url', 'email', 'ownership'],
    group: 'Ops',
    iconName: 'GitMerge',
  },
  {
    id: 'content-scan',
    label: 'Content Scanner',
    description: 'Scan database and files for casino/gambling keywords',
    href: '/wp-admin/content-scanner',
    keywords: ['scan', 'casino', 'slots', 'gambling', 'content', 'keywords'],
    group: 'Ops',
    iconName: 'AlertTriangle',
  },
  {
    id: 'audit-log',
    label: 'Security Audit Log',
    description: 'View all admin write actions, rejected requests, and security events',
    href: '/wp-admin/security/audit-log',
    keywords: ['audit', 'log', 'security', 'events', 'history', 'rejected', 'violations'],
    group: 'Ops',
    iconName: 'Shield',
  },
  {
    id: 'settings',
    label: 'Settings & Secrets',
    description: 'Generate and manage admin secrets and system configuration',
    href: '/wp-admin/settings',
    keywords: ['settings', 'secrets', 'config', 'api keys', 'security'],
    group: 'Ops',
    iconName: 'Settings',
  },
  {
    id: 'claim-links',
    label: 'Claim Links',
    description: 'Generate /your-agency/t/:token deep-links for agency outreach campaigns',
    href: '/wp-admin/claim-links',
    keywords: ['claim', 'links', 'token', 'your agency', 'outreach', 'campaign', 'deep link'],
    group: 'Ops',
    iconName: 'Link2',
  },
];

export const TOOL_GROUPS = ['Content', 'Monetization', 'Email', 'Ops'] as const;
