// Shared Primary-Category-label -> existing tool_categories.slug map used by
// batches 11, 12, 13, 10 (2026-07 commercial-outreach manifests). Every label
// resolves to one of the 75 categories already in the catalog (no schema
// changes needed for these batches) — thin/niche labels fold into the
// closest generic existing category rather than proliferating new ones,
// matching the pattern established in batch 6's resolveCategory().
export const LABEL_MAP = {
  // Batch 11
  'AI & Automation': 'automation',
  'Customer Support': 'customer-support',
  'Finance & Billing': 'finance',
  'Marketing': 'marketing',
  'Sales & CRM': 'crm',
  'Security & Identity': 'security',
  // Batch 12
  'Analytics': 'analytics',
  'Automation': 'automation',
  'Developer Platform': 'developer-tools',
  'Forms & Surveys': 'forms',
  'HR Software': 'hr',
  'Project Management': 'project-management',
  'Testing & QA': 'devops',
  // Batch 13
  'Business Software': 'productivity',
  'Cloud Infrastructure': 'hosting',
  'Databases & Data Infrastructure': 'databases',
  'Design & Media': 'design',
  'Education Software': 'online-learning',
  'Email & Communication': 'communication',
  'Healthcare Software': 'healthcare',
  'Monitoring & Observability': 'devops',
  'Property Software': 'productivity',
  'Search': 'productivity',
  // Batch 10
  'AI & Content': 'ai-writing',
  'AI Video & Creative': 'ai-video-generation',
  'API Development': 'api-tools',
  'Account-Based Marketing': 'marketing',
  'Accounting': 'accounting',
  'Advertising': 'marketing',
  'Agency Management': 'project-management',
  'Assessments': 'hr',
  'Async Video': 'video-conferencing',
  'Audio & Podcasting': 'podcast-hosting',
  'B2B Attribution': 'analytics',
  'Backend as a Service': 'developer-tools',
  'Business Intelligence': 'business-intelligence',
  'CI/CD': 'devops',
  'CRM': 'crm',
  'CRM & Marketing': 'crm',
  'Client Management': 'crm',
  'Client Portal': 'productivity',
  'Cloud Platform': 'hosting',
  'Code Quality': 'devops',
  'Collaboration': 'collaboration',
  'Compliance': 'security',
  'Construction Management': 'project-management',
  'Contact Center': 'customer-support',
  'Contract Management': 'documents-esignature',
  'Course Platforms': 'online-learning',
  'Customer Analytics': 'analytics',
  'Customer Data Platform': 'analytics',
  'Customer Engagement': 'marketing',
  'Customer Feedback': 'surveys',
  'Customer Success': 'customer-support',
  'Customer Support AI': 'customer-support',
  'Cybersecurity': 'security',
  'Data Analytics': 'analytics',
  'Data Integration': 'databases',
  'Database & Workflow': 'databases',
  'Developer Email': 'email-marketing',
  'Diagramming': 'productivity',
  'Digital Experience': 'analytics',
  'ERP': 'erp',
  'Ecommerce': 'ecommerce',
  'Ecommerce Analytics': 'analytics',
  'Ecommerce Marketing': 'ecommerce',
  'Ecommerce Personalization': 'ecommerce',
  'Ecommerce Subscriptions': 'ecommerce',
  'Education Management': 'online-learning',
  'Email Marketing': 'email-marketing',
  'Employee Experience': 'hr',
  'Expense Management': 'finance',
  'Experience Management': 'surveys',
  'Experimentation': 'analytics',
  'FP&A': 'finance',
  'Feature Management': 'devops',
  'Field Service Management': 'field-service',
  'Financial Operations': 'finance',
  'Freelance Management': 'project-management',
  'Fulfillment': 'ecommerce',
  'Global HR': 'hr',
  'Healthcare Practice Management': 'healthcare',
  'Hospitality Software': 'productivity',
  'Identity Management': 'security',
  'Incident Management': 'devops',
  'Integration Platform': 'developer-tools',
  'Internal Tools': 'low-code',
  'Knowledge Management': 'knowledge-base',
  'Landing Pages': 'website-builders',
  'Learning Management': 'online-learning',
  'Legal AI': 'legal',
  'Legal CRM': 'legal',
  'Legal Practice Management': 'legal',
  'Maintenance Management': 'field-service',
  'Marketing Analytics': 'analytics',
  'Marketing Attribution': 'analytics',
  'Media Intelligence': 'analytics',
  'Merchant of Record': 'payments',
  'Networking & Security': 'security',
  'Newsletter Software': 'email-marketing',
  'No-Code': 'no-code',
  'Observability': 'devops',
  'Password Managers': 'password-managers',
  'Payroll & HR': 'hr',
  'Performance Management': 'hr',
  'Personalization': 'marketing',
  'Post-Purchase': 'ecommerce',
  'Practice Management': 'healthcare',
  'Privacy & Compliance': 'security',
  'Product Analytics': 'analytics',
  'Professional Services Automation': 'project-management',
  'Property Management': 'productivity',
  'Proposals & Contracts': 'documents-esignature',
  'Publishing Analytics': 'analytics',
  'Recruiting': 'recruitment',
  'Recruiting AI': 'recruitment',
  'Restaurant Software': 'retail-pos',
  'Returns Management': 'ecommerce',
  'Revenue Intelligence': 'analytics',
  'Reverse ETL': 'databases',
  'SEO': 'seo',
  'SEO & Content': 'seo',
  'Sales Enablement': 'sales',
  'Sales Engagement': 'sales',
  'Sales Intelligence': 'sales',
  'Sales Productivity': 'sales',
  'Scheduling': 'scheduling',
  'Shipping': 'ecommerce',
  'Site Search': 'ecommerce',
  'Social Listening': 'social-media',
  'Social Media': 'social-media',
  'Subscription Billing': 'payments',
  'Talent Intelligence': 'recruitment',
  'Technical Assessments': 'recruitment',
  'Telehealth': 'healthcare',
  'User Research': 'product-management',
  'Video & Creative': 'video-editing',
  'Video Conferencing': 'video-conferencing',
  'Web Analytics': 'analytics',
  'Website Builder': 'website-builders',
  'Wellness Business Software': 'healthcare',
  'Work Management': 'project-management',
};

export function resolveCategory(label, name) {
  const mapped = LABEL_MAP[label];
  if (!mapped) throw new Error(`No mapping for category label: "${label}" (tool: ${name})`);
  return mapped;
}

// Tier -> approximate strategic_metadata scores. The source manifests gave
// per-row Commercial Fit / Paid Listing Potential / SEO Potential / Gappsy
// Opportunity values that were near-constant within each tier bucket
// (Tier A always 9/9/8/8.7, Tier B always 8/8/8/8.0); Tier C varied slightly
// between two sub-buckets (9/6/8/7.7 and 8/5/8/7.0) which this collapses to
// one representative value — harmless since these are internal prioritization
// heuristics, not user-facing claims.
export const TIER_SCORES = {
  A: { traffic: 9, seo: 8, paid: 9, opportunity: 8.7, tier: 'Tier A — Strong sales prospect' },
  B: { traffic: 8, seo: 8, paid: 8, opportunity: 8.0, tier: 'Tier B — Good commercial prospect' },
  C: { traffic: 8, seo: 8, paid: 6, opportunity: 7.4, tier: 'Tier C — Traffic value, harder sale' },
};
