import {
  MousePointerClick,
  LayoutTemplate,
  Palette,
  Wand2,
  PenLine,
  Brush,
  Eraser,
  Maximize2,
  Sparkles,
  PlayCircle,
  ImageMinus,
  Image,
  Presentation,
  Video,
  PenSquare,
  FileText,
  Clapperboard,
  Film,
  Music,
  Printer,
  Truck,
  Globe,
  Link,
  CalendarClock,
  Share2,
  BarChart3,
  Users2,
  MessageSquare,
  History,
  ShieldCheck,
  Lock,
  FolderOpen,
  Blocks,
  Plug,
  Smartphone,
  Monitor,
  Chrome,
  Type,
  Camera,
  Table,
  type LucideIcon,
} from 'lucide-react';

// String-keyed lookup so content modules (src/data/toolContent/*) can name an
// icon by string rather than importing lucide-react components directly —
// the same convention already used for tool_categories.icon in the database.
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  MousePointerClick,
  LayoutTemplate,
  Palette,
  Wand2,
  PenLine,
  Brush,
  Eraser,
  Maximize2,
  Sparkles,
  PlayCircle,
  ImageMinus,
  Image,
  Presentation,
  Video,
  PenSquare,
  FileText,
  Clapperboard,
  Film,
  Music,
  Printer,
  Truck,
  Globe,
  Link,
  CalendarClock,
  Share2,
  BarChart3,
  Users2,
  MessageSquare,
  History,
  ShieldCheck,
  Lock,
  FolderOpen,
  Blocks,
  Plug,
  Smartphone,
  Monitor,
  Chrome,
  Type,
  Camera,
  Table,
};

export function resolveLucideIcon(name: string): LucideIcon | undefined {
  return LUCIDE_ICON_MAP[name];
}
