/**
 * Smart Routing Ensure Discount
 *
 * Creates a discount offer for smart routing if one doesn't already exist.
 * Reuses existing discount-offer-create logic.
 */

import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    const {
      agency_id,
      agency_slug,
      state_slug,
      discount_type = 'percentage',
      discount_value = 20,
      max_uses = 1,
    } = await req.json();

    if (!agency_id) {
      return new Response(
        JSON.stringify({ error: 'agency_id is required' }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Check if active discount already exists
    const { data: existingOffer } = await supabase
      .from('discount_offers')
      .select('token, id')
      .eq('agency_id', agency_id)
      .eq('is_active', true)
      .gte('expires_at', new Date().toISOString())
      .maybeSingle();

    if (existingOffer) {
      const appUrl = Deno.env.get('VITE_APP_URL') || 'https://gappsy.com';
      // Use public /offer/{token} URL — OfferRedirectPage enriches with full
      // agency context before forwarding to /activation/upgrade.
      const url = `${appUrl}/offer/${existingOffer.token}`;

      return new Response(
        JSON.stringify({
          ok: true,
          url,
          offer_id: existingOffer.id,
          created: false,
        }),
        {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Create new discount using internal service-to-service call
    const createResponse = await fetch(`${supabaseUrl}/functions/v1/discount-offer-create`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supabaseKey}`,
      },
      body: JSON.stringify({
        agency_id,
        agency_slug,
        state_slug,
        discount_type,
        discount_value,
        max_uses,
        created_by: 'smart_routing',
        internal_note: 'Auto-generated by smart routing',
      }),
    });

    const createData = await createResponse.json();

    if (!createResponse.ok) {
      return new Response(
        JSON.stringify({ error: createData.error || 'Failed to create discount' }),
        {
          status: createResponse.status,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    return new Response(
      JSON.stringify({
        ok: true,
        url: createData.offer?.url,
        offer_id: createData.offer?.id,
        created: true,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (err) {
    console.error('[smart-routing-ensure-discount] Error:', err);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
