/**
 * Smart Routing Ensure Upgrade
 *
 * Creates an upgrade offer for smart routing if one doesn't already exist.
 * Reuses existing upgrade-offer-create logic.
 */

import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    const {
      agency_id,
      agency_name,
      state_slug,
      old_subscription_id,
      target_rank,
      extra_discount_cents = 0,
    } = await req.json();

    if (!agency_id || !agency_name || !state_slug || !target_rank) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields' }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Check if active upgrade offer already exists with matching target_rank
    const { data: existingOffer } = await supabase
      .from('upgrade_offers')
      .select('checkout_url, id')
      .eq('agency_id', agency_id)
      .eq('state_slug', state_slug)
      .eq('target_rank', target_rank)
      .in('status', ['pending_checkout', 'completed'])
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (existingOffer && existingOffer.checkout_url) {
      return new Response(
        JSON.stringify({
          ok: true,
          checkout_url: existingOffer.checkout_url,
          offer_id: existingOffer.id,
          created: false,
        }),
        {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Create new upgrade offer using internal service-to-service call
    const createResponse = await fetch(`${supabaseUrl}/functions/v1/upgrade-offer-create`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${supabaseKey}`,
        'x-admin-token': supabaseKey, // Use service role key as admin auth
      },
      body: JSON.stringify({
        agency_id,
        agency_name,
        state_slug,
        old_subscription_id,
        target_rank,
        extra_discount_cents,
        notes: 'Auto-generated by smart routing',
        created_by_admin: 'smart_routing',
      }),
    });

    const createData = await createResponse.json();

    if (!createResponse.ok) {
      return new Response(
        JSON.stringify({ error: createData.error || 'Failed to create upgrade offer' }),
        {
          status: createResponse.status,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    return new Response(
      JSON.stringify({
        ok: true,
        checkout_url: createData.checkout_url,
        offer_id: createData.offer_id,
        created: true,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (err) {
    console.error('[smart-routing-ensure-upgrade] Error:', err);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
